# Generated by Django 5.0.7 on 2024-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100)),
                ("task_description", models.CharField(max_length=500)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
