# Generated by Django 5.0.7 on 2024-07-23 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_usertodolink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserTodoLink",
        ),
    ]
