# Generated by Django 5.0.7 on 2024-07-23 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_usertodolink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertodolink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("b4f2b7a6-6d48-4570-b251-5fb3dbdebff8"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
