# Generated by Django 5.0.7 on 2024-07-23 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_usertodolink_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usertodolink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("89d245f3-28e4-4b6f-895c-3b97b2508a0a"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
