# Generated by Django 5.0.7 on 2024-07-25 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_todo_user_alter_usertodolink_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertodolink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("c6ec59e6-1698-4dd1-99dd-7e448a34cdb4"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="todo",
            table="todo",
        ),
    ]
