# Generated by Django 5.0.7 on 2024-07-25 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_todo_options_alter_usertodolink_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["-status"]},
        ),
        migrations.AlterField(
            model_name="usertodolink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("51d3c2ba-f0fe-49ab-bb19-25bdad963540"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
